name: "Install Python Dependencies"
description: "Sets up Python Virtual Environment and installs dependencies, with caching"
inputs:
  repo-path:
    description: "Path where the repository is located"
    required: true
  requirements-file:
    description: "Path to the requirements.txt file"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout Delivery Pipeline Repository
      uses: actions/checkout@v4

    - name: Cache Python virtual environment
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.repo-path }}/venv
        key: venv-${{ runner.os }}-${{ hashFiles('${{ inputs.repo-path }}/requirements.txt') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install Dependencies if Cache Miss
      run: |
        echo "Setting up Python Virtual Environment..."
        python3 -m venv ${{ inputs.repo-path }}/venv
        source ${{ inputs.repo-path }}/venv/bin/activate
        pip3 install -r ${{ inputs.repo-path }}/requirements.txt
      working-directory: ${{ inputs.repo-path }}
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Dependencies if Cache Hit
      run: |
        echo "Virtual Environment and dependencies already set up from cache."
      if: steps.cache.outputs.cache-hit == 'true'
