name: "Install Dependencies"
description: "Set up Python environment and install dependencies"

runs:
  using: composite
  steps:
    - name: Print Step Name
      run: echo "Installing Python dependencies..."
      shell: bash

    - name: Clone Python Greetings Repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Set up Python Virtual Environment
      run: |
        echo "Creating virtual environment..."
        python3 -m venv venv
      working-directory: python-greetings
      shell: bash

    - name: Activate Virtual Environment & Install Dependencies
      run: |
        echo "Installing dependencies..."
        source venv/bin/activate
        pip3 install -r requirements.txt
      working-directory: python-greetings
      shell: bash

    - name: Cache Virtual Environment
      uses: actions/cache@v3
      with:
        path: python-greetings/venv
        key: venv-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          venv-${{ runner.os }}-
