name: "Install Python Dependencies"
description: "Sets up Python Virtual Environment and installs dependencies, with caching"
inputs:
  repo-path:
    description: "Path where the repository is located"
    required: true
  requirements-file:
    description: "Path to the requirements.txt file"
    required: true

runs:
  using: composite
  steps:

    - name: Cache Python virtual environment
      id: cache-venv
      uses: actions/cache@v3
      with:
        path: ${{ inputs.repo-path }}/venv
        key: venv-${{ runner.os }}-${{ hashFiles(inputs.requirements-file) }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install Dependencies if Cache Miss
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        echo "Setting up Python Virtual Environment..."
        python3 -m venv ${{ inputs.repo-path }}/venv
        source ${{ inputs.repo-path }}/venv/bin/activate
        pip3 install -r ${{ inputs.requirements-file }}
      working-directory: ${{ inputs.repo-path }}
      shell: bash

    - name: Install Dependencies if Cache Hit
      if: steps.cache-venv.outputs.cache-hit == 'true'
      run: echo "Virtual Environment and dependencies already set up from cache."
      shell: bash
