name: "Deploy Python App"
description: "Deploys the Python app using pm2"

inputs:
  environment:
    description: "Target environment (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port for the service"
    required: true

runs:
  using: composite
  steps:
    - name: Print Step Name
      run: echo "Starting deployment to ${{ inputs.environment }}..."
      shell: bash

    - name: Clone Python Greetings Repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Restore Cached Virtual Environment
      uses: actions/cache@v3
      with:
        path: python-greetings/venv
        key: venv-${{ runner.os }}-${{ github.run_id }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Activate Virtual Environment
      run: |
        echo "Activating virtual environment..."
        source venv/bin/activate
        pip3 freeze --local
      working-directory: python-greetings
      shell: bash

    - name: Stop Existing Service
      run: pm2 delete greetings-app-${{ inputs.environment }} || true
      working-directory: python-greetings
      shell: bash

    - name: Deploy Application
      run: |
        echo "Deploying to ${{ inputs.environment }} on port ${{ inputs.port }}..."
        pm2 start 'venv/bin/python3 app.py' --name greetings-app-${{ inputs.environment }} --port ${{ inputs.port }} 
      working-directory: python-greetings
      shell: bash
