name: "Deploy Application"
description: "Deploy Python app with pm2"

inputs:
  environment:
    required: true
  port:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clone Python Greetings Repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service
      run: pm2 delete greetings-app-${{ inputs.environment }} || true
      working-directory: python-greetings

    - name: Start service with pm2
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      working-directory: python-greetings

