name: "Deploy Application"
description: "Deploys Python Greetings application using pm2"
inputs:
  environment:
    description: "Target environment (dev, staging, preprod, prod)"
    required: true
  port:
    description: "Port number for the application"
    required: true
runs:
  using: composite
  steps:
    - name: Checkout Delivery Pipeline Repository
      uses: actions/checkout@v4

    - name: Clone Python Greetings Repository
      uses: actions/checkout@v4
      with:
        repository: mtararujs/python-greetings
        path: python-greetings

    - name: Stop existing service
      run: |
        echo "Stopping existing service in ${{ inputs.environment }}..."
        pm2 delete greetings-app-${{ inputs.environment }} || true
      working-directory: python-greetings
      shell: bash

    - name: Deploy application
      run: |
        echo "Deploying application to ${{ inputs.environment }} environment..."
        pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      working-directory: python-greetings
      shell: bash
